dtb-$(CONFIG_CAMERA_CROWN) += \
       exynos9810-crownlte_eur_open_17.dtb \
       exynos9810-crownlte_eur_open_18.dtb \
       exynos9810-crownlte_eur_open_19.dtb \
			 exynos9810-crownlte_eur_open_21.dtb \
			 exynos9810-crownlte_eur_open_23.dtb \
			 exynos9810-crownlte_eur_open_24.dtb \
			 exynos9810-crownlte_eur_open_25.dtb \
			 exynos9810-crownlte_eur_open_26.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
